{% set name = "oslo.log" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc94aabdb50e1e2571c6cbc4b399694a0541576735908a984a0223a9e1fbdb3e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - convert-json = oslo_log.cmds.convert_json:main
  skip: true  # [py < 38]

requirements:
  host:
    - pbr >=3.1.1
    - pip
    - python
  run:
    - python
    - pbr >=3.1.1
    - oslo.config >=5.2.0
    - oslo.context >=2.20.0
    - oslo.i18n >=3.20.0
    - oslo.utils >=3.36.0
    - oslo.serialization >=2.25.0
    - debtcollector >=1.19.0
    - pyinotify >=0.9.6  # [linux]
    - python-dateutil >=2.7.0

test:
  imports:
    - oslo_log
  commands:
    - convert-json -h

about:
  home: https://docs.openstack.org/oslo.log/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library provides standardized configuration for all openstack projects
  dev_url: https://bugs.launchpad.net/oslo.log

extra:
  recipe-maintainers:
    - tschoonj
