{% set name = "oslo.log" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b151d9c3f2b2ecc12c06d0fb7dbf2e9047afdaec3644827fa1e10b354369563

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - convert-json = oslo_log.cmds.convert_json:main
  noarch: python

requirements:
  host:
    - pbr >=3.1.1
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pbr >=3.1.1
    - oslo.config >=5.2.0
    - oslo.context >=2.21.0
    - oslo.i18n >=3.20.0
    - oslo.utils >=3.36.0
    - oslo.serialization >=2.25.0
    - python-dateutil >=2.7.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - oslo_log
  commands:
    - convert-json -h

about:
  home: https://docs.openstack.org/oslo.log/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A library provides standardized configuration for all openstack projects
  dev_url: https://bugs.launchpad.net/oslo.log

extra:
  recipe-maintainers:
    - tschoonj
